AWSTemplateFormatVersion: '2010-09-09'
Resources:
  # Customer User Pool
  CustomerUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: CustomerPool
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true
      EmailVerificationSubject: "Your verification code"
      EmailVerificationMessage: "Your verification code is {####}."
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK
        EmailMessageByLink: "Click the link below to verify your email address: {##Verify Email##}"
        EmailSubjectByLink: "Verify your email address"

  CustomerUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: AuthpoolforCustomers
      UserPoolId: !Ref CustomerUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - USER_PASSWORD_AUTH
      SupportedIdentityProviders:
        - COGNITO

  CustomerUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: customer-auth-serverlessgrp33
      UserPoolId: !Ref CustomerUserPool

  # Agent User Pool
  AgentUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: AgentPool
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true
      EmailVerificationSubject: "Your verification code"
      EmailVerificationMessage: "Your verification code is {####}."
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK
        EmailMessageByLink: "Click the link below to verify your email address: {##Verify Email##}"
        EmailSubjectByLink: "Verify your email address"

  AgentUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: AuthpoolforAgents
      UserPoolId: !Ref AgentUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - USER_PASSWORD_AUTH
      SupportedIdentityProviders:
        - COGNITO

  AgentUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: agent-auth-serverlessgrp33
      UserPoolId: !Ref AgentUserPool

Outputs:
  CustomerUserPoolId:
    Description: The Customer User Pool ID
    Value: !Ref CustomerUserPool

  CustomerUserPoolClientId:
    Description: The Customer User Pool Client ID
    Value: !Ref CustomerUserPoolClient

  AgentUserPoolId:
    Description: The Agent User Pool ID
    Value: !Ref AgentUserPool

  AgentUserPoolClientId:
    Description: The Agent User Pool Client ID
    Value: !Ref AgentUserPoolClient

